# Site wide configuration

title: Archethought
locale: en_US
description: Discussions about Archethought technology solutions and community building.
logo: arch-logo.png
search: true
url: https://archethought.github.io

# Jekyll  configuration
# theme: https://github.com/the-development/flex

name: Flex
markdown: kramdown
highligher: rouge

